<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $data = [
            // Artworks
            [
                'name'         => '727',
                'description'  => 'A vibrant contemporary piece by Takashi Murakami featuring his signature colorful style.',
                'price'        => 15000.00,
                'category'     => 'artwork',
                'artist'       => 'Takashi Murakami',
                'image_url'    => 'https://i.pinimg.com/736x/ac/8c/79/ac8c790b5b99c2d8ae52bd4f87f4062e.jpg',
                'stock'        => 1,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'Lady Murasaki Writing at Her Desk',
                'description'  => 'Traditional Japanese artwork depicting the famous author in classical Edo style.',
                'price'        => 8500.00,
                'category'     => 'artwork',
                'artist'       => 'Tosa Mitsuoki',
                'image_url'    => 'https://i.pinimg.com/736x/0b/f7/31/0bf73170624ab7a124adef98ebf4461d.jpg',
                'stock'        => 1,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'immer im Blick',
                'description'  => 'An abstract painting suggesting a cat-like figure whose eyes seem to quietly follow the viewer.',
                'price'        => 25000.00,
                'category'     => 'artwork',
                'artist'       => 'Margit Schick',
                'image_url'    => 'https://www.singulart.com/images-sh/eyJidWNrZXQiOiJzaW5ndWxhcnQtd2Vic2l0ZS1wcm9kIiwia2V5IjoiYXJ0d29ya3NcL3YyXC9jcm9wcGVkXC84MTgxOVwvbWFpblwvem9vbVwvMjU3MDYzMV9iMDgyNmNhMzA1YTIzYjJkNmM3NWYyZTVkODllMmI1YS5qcGVnIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjoxNTM0LCJoZWlnaHQiOjYwMCwiZml0IjoiaW5zaWRlIiwiYmFja2dyb3VuZCI6bnVsbH0sInRvRm9ybWF0Ijoid2VicCJ9fQ==?signature=c89ecad921bdc9b06901f23285232388128c31a64bc5acb82836ad57eb777bf8',
                'stock'        => 1,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'My African Dream - The Longing',
                'description'  => 'A colorful painting by Karnish Art with Oil Canvas from South Africa, 2021.',
                'price'        => 10750.00,
                'category'     => 'artwork',
                'artist'       => 'Karnish Art',
                'image_url'    => 'https://www.singulart.com/images/artworks/v2/cropped/5723/main/zoom/1068351_dac4f9a7afe15351424fffcdd5103ad8.jpeg',
                'stock'        => 1,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'reflective energy',
                'description'  => 'A painting from Cepoi from Spain, 2024 of Oil on Canvas.',
                'price'        => 11850.00,
                'category'     => 'artwork',
                'artist'       => 'Ana Maria Cepoi',
                'image_url'    => 'https://www.singulart.com/images/artworks/v2/cropped/8307/main/zoom/1935006_4d97da89d82ac7fe5c0fc4c7828cc9b7.jpeg',
                'stock'        => 1,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'Flower',
                'description'  => 'A painting from NATXA from Germany, 2024 of Acrylic Paint on Canvas.',
                'price'        => 14400.00,
                'category'     => 'artwork',
                'artist'       => 'Marina Fedorova',
                'image_url'    => 'https://www.singulart.com/images-sh/eyJidWNrZXQiOiJzaW5ndWxhcnQtd2Vic2l0ZS1wcm9kIiwia2V5IjoiYXJ0d29ya3NcL3YyXC9jcm9wcGVkXC8xMjE1NVwvbWFpblwvem9vbVwvMjQ3NjU2Ml9iNjA1ZTllOGE2ZDc0ZGFjMmMwMDMxYTc5ZjAyZThjMi5qcGVnIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjoxNTM0LCJoZWlnaHQiOjYwMCwiZml0IjoiaW5zaWRlIiwiYmFja2dyb3VuZCI6bnVsbH0sInRvRm9ybWF0Ijoid2VicCJ9fQ==?signature=2eb0a894df004268509041dc6315a46d4fa2a6f7ec62aa334a3f4600d5117408',
                'stock'        => 1,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'Angel of Hope',
                'description'  => 'This angel symbolizes all who work to bring hope to a darkening world.',
                'price'        => 85900.00,
                'category'     => 'artwork',
                'artist'       => 'Michael Malmn',
                'image_url'    => 'https://mikemalm.com/cdn/shop/files/AgentofHopesm_1534x.jpg?v=1769037612',
                'stock'        => 1,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'a view from malibu',
                'description'  => '12" x 24" oil on Canvas',
                'price'        => 106000.00,
                'category'     => 'artwork',
                'artist'       => 'Calvin Liang',
                'image_url'    => 'https://faso.artfulcdn.com/17387_6063551xl.jpg?sold=Sold&hdots=False&v=202504230048&cv=202012050148',
                'stock'        => 1,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'canal scene',
                'description'  => '16" x 20" oil on Canvas',
                'price'        => 24500.00,
                'category'     => 'artwork',
                'artist'       => 'Calvin Liang',
                'image_url'    => 'https://faso.artfulcdn.com/17387_4841070xl.jpg?sold=Sold&hdots=False&v=202209222253&cv=202012050148',
                'stock'        => 1,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'reflections, venice',
                'description'  => '18" x 24" of oil in canvas by Liang',
                'price'        => 94000.00,
                'category'     => 'artwork',
                'artist'       => 'Calvin Liang',
                'image_url'    => 'https://faso.artfulcdn.com/17387_866337xl.jpg?sold=Sold&hdots=False&v=202012050148&cv=202012050148',
                'stock'        => 1,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],

            // Artbooks
            [
                'name'         => 'Symbols of Japan by Merrily Baird',
                'description'  => 'A comprehensive guide to traditional Japanese symbols and their meanings.',
                'price'        => 3000.00,
                'category'     => 'artbook',
                'artist'       => 'Merrily Baird',
                'image_url'    => 'https://m.media-amazon.com/images/I/81NxXiPzQ1L._AC_UF1000,1000_QL80_.jpg',
                'stock'        => 25,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'MERCURY by Entei Ryu',
                'description'  => 'Sculptural works showcasing dynamic movement and modern artistic expression.',
                'price'        => 5000.00,
                'category'     => 'artbook',
                'artist'       => 'Entei Ryu',
                'image_url'    => 'https://japanese-creative-books.com/wp-content/uploads/2025/07/MERCURY-Entei-Ryu-Sculptural-Works-757x1024.jpg.webp',
                'stock'        => 15,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'My Hero Academia Ultra Artworks',
                'description'  => 'Official artbook featuring character designs and illustrations from the popular manga series.',
                'price'        => 6000.00,
                'category'     => 'artbook',
                'artist'       => 'Kohei Horikoshi',
                'image_url'    => 'https://japanresell.fr/cdn/shop/files/my-hero-academia-ultra-artworks-893922.jpg?v=1745328958&width=1024',
                'stock'        => 30,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'The Artwork of Berserk',
                'description'  => 'A stunning collection of artwork from the legendary dark fantasy manga series.',
                'price'        => 9000.00,
                'category'     => 'artbook',
                'artist'       => 'Miura Kentaro',
                'image_url'    => 'https://japanresell.fr/cdn/shop/products/art-book-officiel-the-artwork-of-berserk-berserk-exhibition-220146.jpg?v=1678786386&width=1024',
                'stock'        => 20,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'The Art of Miyazaki\'s Spirited Away',
                'description'  => 'A beautifully illustrated guide to the concept art and animation of Studio Ghibli’s classic film.',
                'price'        => 4500.00,
                'category'     => 'artbook',
                'artist'       => 'Hayao Miyazaki',
                'image_url'    => 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1435336738i/429853.jpg',
                'stock'        => 20,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'Dragon Ball Artbook',
                'description'  => 'Comprehensive collection of character designs, illustrations, and storyboards from the iconic manga and anime series.',
                'price'        => 5500.00,
                'category'     => 'artbook',
                'artist'       => 'Akira Toriyama',
                'image_url'    => 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1731245139i/66297.jpg',
                'stock'        => 25,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'Artbook The Legend of Zelda Hyrule Graphics 30th Anniversary',
                'description'  => 'A deep dive into the visual development, world-building, and concept art behind the beloved video game series.',
                'price'        => 4800.00,
                'category'     => 'artbook',
                'artist'       => 'Nintendo Art Team',
                'image_url'    => 'https://japondemande.com/cdn/shop/files/product_book_artbook_the-legend-of-zelda_hyrule-graphics.jpg?v=1721788551',
                'stock'        => 15,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'Painting the Worlds of Studio Ghibli',
                'description'  => 'A curated collection of original storyboards and sketches from multiple Studio Ghibli films.',
                'price'        => 5200.00,
                'category'     => 'artbook',
                'artist'       => 'Studio Ghibli',
                'image_url'    => 'https://admin.itsnicethat.com/images/TxEt6TDGnshEEdgwQL_awsj6HXY=/275165/format-webp%7Cwidth-2880/painting_the_worlds_of_studio_ghibli_6.jpg',
                'stock'        => 18,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'The Art of Attack on Titan',
                'description'  => 'Showcases the concept art, character designs, and world illustrations from the epic dark fantasy series.',
                'price'        => 6000.00,
                'category'     => 'artbook',
                'artist'       => 'Hajime Isayama',
                'image_url'    => 'https://m.media-amazon.com/images/I/814MphCgUhL._AC_UF1000,1000_QL80_.jpg',
                'stock'        => 22,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'The Art of Demon Slayer',
                'description'  => 'Features exquisite illustrations, character designs, and behind-the-scenes artwork from the popular anime.',
                'price'        => 5800.00,
                'category'     => 'artbook',
                'artist'       => 'Koyoharu Gotouge',
                'image_url'    => 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1720269708i/62976864.jpg',
                'stock'        => 20,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],

            // Merchandise
            [
                'name'         => 'Edo Ember Gallery Tote Bag',
                'description'  => 'Canvas tote bag featuring our signature flame emblem and gallery logo.',
                'price'        => 25.00,
                'category'     => 'merchandise',
                'artist'       => null,
                'image_url'    => 'https://i.pinimg.com/control1/1200x/2b/2e/72/2b2e72af4b0a2fd4db110b8f35a1aab4.jpg',
                'stock'        => 50,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'Edo Ember Gallery Coffee Mug',
                'description'  => 'Ceramic mug featuring the gallery’s flame emblem, perfect for your morning coffee.',
                'price'        => 15.00,
                'category'     => 'merchandise',
                'artist'       => null,
                'image_url'    => 'https://i.pinimg.com/474x/f9/bc/b6/f9bcb6d04d4a5ae9e81ad4444cf0f795.jpg',
                'stock'        => 40,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'Edo Ember Gallery Notebook',
                'description'  => 'Hardcover notebook with gallery branding, ideal for sketches and notes.',
                'price'        => 12.00,
                'category'     => 'merchandise',
                'artist'       => null,
                'image_url'    => 'https://i.pinimg.com/control1/1200x/31/a2/2e/31a22e07a125d8788e7739ac1371fa58.jpg',
                'stock'        => 60,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'Edo Ember Gallery Keychain',
                'description'  => 'Metal keychain with the signature gallery flame emblem.',
                'price'        => 15.00,
                'category'     => 'merchandise',
                'artist'       => null,
                'image_url'    => 'https://i.pinimg.com/control1/736x/dc/ae/5c/dcae5c3266a264577a873f80f326031b.jpg',
                'stock'        => 100,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'Edo Ember Gallery Enamel Pin',
                'description'  => 'Stylish enamel pin featuring the gallery logo, perfect for jackets or bags.',
                'price'        => 11.00,
                'category'     => 'merchandise',
                'artist'       => null,
                'image_url'    => 'https://i.pinimg.com/1200x/8a/b8/4f/8ab84ff2882be85933cee136c7afedd4.jpg',
                'stock'        => 80,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'Edo Ember Gallery Hoodie',
                'description'  => 'Comfy cotton hoodie with the gallery emblem on the chest and back.',
                'price'        => 450.00,
                'category'     => 'merchandise',
                'artist'       => null,
                'image_url'    => 'https://i.pinimg.com/control1/736x/32/59/84/32598425f250f4722bfcc6366c0c983c.jpg',
                'stock'        => 30,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'Edo Ember Gallery Hat',
                'description'  => 'Adjustable beret with strap and heart accesories',
                'price'        => 150.00,
                'category'     => 'merchandise',
                'artist'       => null,
                'image_url'    => 'https://i.pinimg.com/736x/41/08/49/410849c5fa6445cf82f510979704c276.jpg',
                'stock'        => 50,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'Edo Ember Gallery Dress',
                'description'  => 'Comfortable and stylish dress featuring subtle gallery flame motifs, perfect for casual outings or gallery visits.',
                'price'        => 550.00,
                'category'     => 'merchandise',
                'artist'       => null,
                'image_url'    => 'https://i.pinimg.com/control1/1200x/e2/b0/1b/e2b01bbb9f1b4a85a3a296890c6f7cfc.jpg',
                'stock'        => 25,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'Edo Ember Gallery Sticker Pack',
                'description'  => 'Set of 10 assorted stickers featuring gallery logos and artwork motifs.',
                'price'        => 25.00,
                'category'     => 'merchandise',
                'artist'       => null,
                'image_url'    => 'https://i.pinimg.com/736x/49/aa/31/49aa31053a55bb8cf4c6ea4f32bb509b.jpg',
                'stock'        => 120,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'name'         => 'Edo Ember Gallery Water Bottle',
                'description'  => 'Reusable stainless steel water bottle with a cute bear for a logo',
                'price'        => 160.00,
                'category'     => 'merchandise',
                'artist'       => null,
                'image_url'    => 'https://i.pinimg.com/736x/9e/8b/89/9e8b89d7846ad41aa832303e83f1b31a.jpg',
                'stock'        => 35,
                'is_available' => 1,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
        ];

        // Insert data
        $this->db->table('products')->insertBatch($data);
    }
}
